name: maharshi_chat
description: A visually appealing chat app frontend built with Flutter.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.5+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust the SDK version based on your Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # For iOS-style icons
  http: ^1.3.0
  provider: ^6.0.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # For linting and code analysis
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#000000"  # Black background
  android: true
  ios: true
  web: true
  fullscreen: true  # Optional: Set to true if you want a fullscreen splash

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf