// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qsyS00xQ8mvYI4AL3TaIQFYNV2e_emw',
    appId: '1:165571075689:web:b28d6668175328f5730cf8',
    messagingSenderId: '165571075689',
    projectId: 'mgpt-50f49',
    authDomain: 'mgpt-50f49.firebaseapp.com',
    storageBucket: 'mgpt-50f49.firebasestorage.app',
    measurementId: 'G-8FPYZHZH2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIn4xM2a7yBnO7AArzetMs1pHDWkO0q34',
    appId: '1:165571075689:android:3d76088b34e19c5c730cf8',
    messagingSenderId: '165571075689',
    projectId: 'mgpt-50f49',
    storageBucket: 'mgpt-50f49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vjjW4IDhvJ5WWUWDr1VglV6WxRBVbfs',
    appId: '1:165571075689:ios:852c84ecbac8a719730cf8',
    messagingSenderId: '165571075689',
    projectId: 'mgpt-50f49',
    storageBucket: 'mgpt-50f49.firebasestorage.app',
    iosBundleId: 'com.example.maharshiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vjjW4IDhvJ5WWUWDr1VglV6WxRBVbfs',
    appId: '1:165571075689:ios:852c84ecbac8a719730cf8',
    messagingSenderId: '165571075689',
    projectId: 'mgpt-50f49',
    storageBucket: 'mgpt-50f49.firebasestorage.app',
    iosBundleId: 'com.example.maharshiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qsyS00xQ8mvYI4AL3TaIQFYNV2e_emw',
    appId: '1:165571075689:web:9b3e177496462fba730cf8',
    messagingSenderId: '165571075689',
    projectId: 'mgpt-50f49',
    authDomain: 'mgpt-50f49.firebaseapp.com',
    storageBucket: 'mgpt-50f49.firebasestorage.app',
    measurementId: 'G-NPM605WP4K',
  );
}
